# https://docs.docker.com/compose/compose-file/03-compose-file/

version: '3.5'

services:
  app:
    build: .docker/clojure
    working_dir: /app
    volumes:
      - .:/app
      - ./var/clojure:/.clojure
      - ./var/vendor:/.m2
